=== Choucroute-melba/emoji/extensions/handler-manifest.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "HandlerManifest",
  "type": "object",
  "additionalProperties": false,
  "required": ["name", "sites", "targets", "trigger", "sources", "maintainer"],
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "maintainer": {
      "type": "string",
      "minLength": 1
    },
    "sites": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "minItems": 1
    },
    "targets": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "minItems": 1
    },
    "trigger": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "required": ["type"],
            "properties": {
              "type": { "const": "default" }
            }
          },
          {
            "type": "object",
            "additionalProperties": false,
            "required": ["type", "combo"],
            "properties": {
              "type": { "const": "combo" },
              "combo": { "type": "string", "minLength": 1 }
            }
          },
          {
            "type": "object",
            "additionalProperties": false,
            "required": ["type", "key"],
            "properties": {
              "type": { "const": "key" },
              "key": { "type": "string", "minLength": 1 }
            }
          },
          {
            "type": "object",
            "additionalProperties": false,
            "required": ["type", "command"],
            "properties": {
              "type": { "const": "command" },
              "command": { "type": "string", "minLength": 1 }
            }
          }
        ]
      },
      "minItems": 1
    },
    "uri": {
      "anyOf": [
        { "type": "string", "minLength": 1 },
        { "type": "null" }
      ]
    },
    "file": {
      "anyOf": [
        { "type": "string", "minLength": 1 },
        { "type": "null" }
      ]
    },
    "sources": {
      "type": "object",
      "additionalProperties": false,
      "required": ["file", "repo"],
      "properties": {
        "file": { "type": "string", "minLength": 1 },
        "repo": { "type": "string", "minLength": 1 }
      }
    }
  }
}

=== Choucroute-melba/emoji/extensions/manifests/aria.manifest.json
{
  "name": "AriaDiv",
  "maintainer": "Choucroute-melba",
  "sites": ["*"],
  "targets": ["div"],
  "file": "bundled",
  "uri": "bundled",
  "sources": {
    "file": "src/features/aria/handler.ts",
    "repo": "https://github.com/Choucroute-melba/emoji"
  },
  "trigger": [
    {
      "type": "default"
    }
  ]
}

=== Choucroute-melba/emoji/extensions/manifests/iframe.manifest.json
{
  "name": "HTMLIframe",
  "maintainer": "Choucroute-melba",
  "sites": ["*"],
  "targets": ["*"],
  "file": "bundled",
  "uri": "bundled",
  "sources": {
    "file": "src/features/iframe/handler.ts",
    "repo": "https://github.com/Choucroute-melba/emoji"
  },
  "trigger": [
    {
      "type": "default"
    }
  ]
}

=== Choucroute-melba/emoji/extensions/manifests/input.manifest.json
{
  "name": "HTMLInput",
  "maintainer": "Choucroute-melba",
  "sites": ["*"],
  "targets": ["input"],
  "file": "bundled",
  "uri": "bundled",
  "sources": {
    "file": "src/features/input/handler.ts",
    "repo": "https://github.com/Choucroute-melba/emoji"
  },
  "trigger": [
    {
      "type": "default"
    }
  ]
}

=== Choucroute-melba/emoji/extensions/manifests/textarea.manifest.json
{
  "name": "TextArea",
  "maintainer": "Choucroute-melba",
  "sites": ["*"],
  "targets": ["textarea", "div"],
  "file": "bundled",
  "uri": "bundled",
  "sources": {
    "file": "src/features/textarea/handler.ts",
    "repo": "https://github.com/Choucroute-melba/emoji"
  },
  "trigger": [
    {
      "type": "default"
    }
  ]
}

=== Choucroute-melba/emoji/extensions/manifests/freeselector.manifest.json
{
  "name": "FreeSelector",
  "maintainer": "Choucroute-melba",
  "sites": ["*"],
  "targets": ["*"],
  "file": "freeselector.bundle.mjs",
  "uri": "https://raw.githubusercontent.com/Choucroute-melba/emoji/master/extensions/freeselector.bundle.mjs",
  "sources": {
    "file": "extensions/freeselector.ts",
    "repo": "https://github.com/Choucroute-melba/emoji"
  },
  "trigger": [
    {
      "type": "combo",
      "combo": "Ctrl+,"
    },
    {
      "type": "combo",
      "combo": "AltGraph+,"
    }
  ]
}
